version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./data/db:/data/db

  api:
    build:
      context: ./api
      dockerfile: api.Dockerfile
    container_name: api-container
    ports:
      - 6000:6000
    depends_on:
      - mongo
    volumes:
      - ./data/db:/app/data

  cli:
    build:
      context: ./cli
      dockerfile: Dockerfile
    container_name: cli-container
    stdin_open: true
    tty: true
    depends_on:
      - api
    volumes:
      - ./data/import:/app/files
      
  compass:
    image: mongocompass/mongocompass:latest
    container_name: compass-container
    ports:
      - 27017:27017
    depends_on:
      - mongo
