version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - ./data:/data/db

  api:
    build:
      context: ./api
      dockerfile: api.Dockerfile
    container_name: api-container
    ports:
      - 6000:6000
    depends_on:
      - mongo
    volumes:
      - ./data:/app/data

  cli:
    build:
      context: ./cli
      dockerfile: Dockerfile
    container_name: cli-container
    stdin_open: true
    tty: true
    depends_on:
      - api
    volumes:
      - ./data:/app/files
