version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./data/db:/data/db

  api:
    build:
      context: ./api
      dockerfile: api.Dockerfile
    container_name: api-container
    ports:
      - 6000:6000
    depends_on:
      - mongo
    volumes:
      - ./data/db:/app/data

  cli:
    build:
      context: ./cli
      dockerfile: Dockerfile
    container_name: cli-container
    stdin_open: true
    tty: true
    depends_on:
      - api
    volumes:
      - ./data/import:/app/files

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express-container
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongo
